### PR TITLE
Move fmn.rules into fmn.lib

### PR DESCRIPTION
**Pull request by jeremycline**
Right now, FMN exists in several repositories and in several separate
Python packages. This merges the ``fmn.rules`` repository and Python package
into ``fmn.lib``. Currently, ``fmn.rules`` depends on ``fmn.lib`` which
depends on ``fmn.rules``. This circular dependency is a good indication
that they should just be a single package, since neither can work
without the other.

Signed-off-by: Jeremy Cline <jeremy@jcline.org>

### CODE REVIEW

**Comment by pypingou** [comment]
@ralphbean do you remember what it was split this way? iirc it was to allow different release cycle.

That being said, I'm fine with merging them back together.

**Comment by jeremycline** [comment]
I've been thinking a bit about organization.

Current State
-----------------

There are currently 6 repositories for FMN:

- https://github.com/fedora-infra/fmn

- https://github.com/fedora-infra/fmn.consumer

- https://github.com/fedora-infra/fmn.rules

- https://github.com/fedora-infra/fmn.sse

- https://github.com/fedora-infra/fmn.web

- https://github.com/fedora-infra/fmn.lib

There's currently also a package for each one (sans fmn).

New State
-------------

What if we combined fmn.lib, fmn.rules, and fmn.consumer (as a subpackage of fmn.lib, perhaps) into the fmn repository. fmn.sse and fmn.web would remain separate. The new set of repositories would be:

- https://github.com/fedora-infra/fmn (with fmn.lib, fmn.rules, fmn.consumer)

- https://github.com/fedora-infra/fmn.sse (depends on fmn)

- https://github.com/fedora-infra/fmn.web (depends on fmn)

My inclination is to also package fmn as a single Python package, although we could package them separately, depending on how we lay out the repository.

If we want to update just the rules, say, without releasing everything in fmn (maybe a new feature just landed and isn't quite ready), we can just cherrypick the rule commit back to the release tag and make a new minor release. It's not quite as flexible, but I (potentially in my ignorance) think that should cover our needs while significantly reducing the maintenance and packaging complexity.

What are your thoughts?

**Comment by jeremycline** [comment]
I played around with git-subtree a bit and was able to [merge fmn.{lib,consumer,rules} into fmn](https://github.com/jeremycline/fmn/tree/merge-projects). The history is preserved (so you can do things like ``git blame``), but obviously commit messages may refer to issue numbers or PRs on different repositories.

Edit: A slightly less cursory examination shows it didn't actually work as well as I thought :(. The log is there, but the file history isn't actually there.

**Comment by ralphbean** [comment]
Just FYI, the original logic behind splitting out `fmn.rules` was that some other site somewhere might want to have its *own* rules for its *own* fedmsg messages.  The Fedora rules would not apply to their installation.

We have no concrete plans for this, but it might be nice to deploy FMN inside RH some day.  We would need to swap out Fedora's `fmn.rules` with a different one.

FWIW, I think `fmn.rules` was *supposed* to depend on `fmn.lib`.. but `fmn.lib` was never supposed to depend on `fmn.rules`.  Of course, if things have changed - do what you have to.  :)

**Comment by jeremycline** [comment]
Ah okay, that makes sense. I think we can still do that and have a single package. The function that loads the rules already takes a Python path as an argument and we can just make that a configuration option. We could even move the Fedora-specific rules into ``fmn.rules.fedora`` and allow other rulesets in under ``fmn.rules.debian`` or ``fmn.rules.redhat`` if they wanted to add their rules upstream. How does that sound?

**Comment by ralphbean** [comment]
> How does that sound?

:+1:  :)

**Pull request closed without merging**
