### PR TITLE
Add taskotron filter

### PR DESCRIPTION
**Pull request by mkrizek**
https://phab.qadevel.cloud.fedoraproject.org/T673

### CODE REVIEW

**Comment by ralphbean** [comment]
OK, I think we'll need to approach this from a different angle.

The way it's currently written, it will add a *new* filter that excludes everything typically excluded, but it also explicitly includes all of the new taskotron rules.  I think it won't have any effect -- a taskotron message coming in will just be caught by and forwarded based on the existing filter that most messages hit -- the "Events on packages I own" filter.

Take a look at this older alembic upgrade script:  https://github.com/fedora-infra/fmn.lib/blob/develop/alembic/versions/38c9c18d342e_add_new_mdapi_rule.py

It goes and finds everyone's existing "Events on packages I own" filter.. and then add *more* negated rules to it, making it more specific.  (We needed to get everyone's preferences to ignore the *very spammy* new mdapi messages).

For taskotron.. we may need to take a step back for a moment and re-state what it is that we want to do.  What kind of messages do we want people to get by default.. and what kind of messages do we **not** want people to get by default.

**Comment by kparal** [comment]
This is getting really complicated :-)

I believe we only want to notify people, when all of this is true:
* the tasktron result is related to their package
* the task completed is a release-critical task
* the task failed or changed state

We really wanted to add a new filter, because it is a combination of several rules and we can't easily filter out the complementary rules from "Events on packages that I own" filter. So the easiest solution seemed to be to create a separate Taskotron-specific filter (which people can easily tinker with, if they want, as a bonus).

You're right that currently it would have no effect, because all user-related taskotron messages would be allowed in by "Events on packages that I own" filter. So let's add a negated "all taskotron events" rule into that? That way Taskotron messages won't be processed by "Events on packages that I own" filter at all, and we will do all the processing in the new filter that is proposed. Does that work?

**Comment by ralphbean** [comment]
Yes @kparal.  Good proposal.  :)

**Comment by ralphbean** [comment]
@mkrizek, I'm going to close this since @kparal's proposal differs significantly.  If you want to base further patches on this code -- that's cool -- just re-submit it.  Thank you!

**Comment by mkrizek** [comment]
> @mkrizek, I'm going to close this since @kparal's proposal differs significantly. If you want to base further patches on this code -- that's cool -- just re-submit it. Thank you!

@ralphbean I thought we were just going to add one rule (negate taskotron messages) to the existing packages filter in addition to using the existing patch. Did I misunderstand @kparal's proposal?

**Pull request closed without merging**
